name: CI
on: [push]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16', '18']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - run: pnpm install --frozen-lockfile

      - name: Cache node_modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node and install project dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: 'pnpm'

      - name: Lint
        run: pnpm run nx run headless-stepper:lint

      - name: Test
        # run: pnpm run nx run headless-stepper:test # TODO: fix this
        run: pnpm test

      - name: Build
        run: pnpm run build:all
