name: "Coverage"
on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v3

      - name: Set Up Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: npm-

      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        id: jest-coverage
        with:
          output: report-markdown
          package-manager: pnpm
          test-script: pnpm test --skip-nx-cache

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.jest-coverage.outputs.report }}
