name: size
on: [pull_request]
jobs:
  size:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - run: pnpm install --frozen-lockfile

      - name: Cache node_modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node and install project dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: 'pnpm'

      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-script: 'build:lib'
